# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Get code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      
    - name: Get dependencies and build
      run: |
        yarn install
        yarn build
  
    - name: Zip on Ubuntu
      uses: nguyenquyhy/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: build.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        workingDirectory: .
        # List of excluded files/directories
        exclusions: build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: build_output
        path: build.tar.gz
      
